### ISSUE TITLE
design test pytest

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab/pywsdp#11]
Framework:

* https://docs.pytest.org

Example: 

* https://gitlab.com/geoharmonizer_inea/eumap/-/blob/issue_16/tests/test_lucas.py
* https://github.com/mapradix/qcmanager/blob/master/tests/test_tc1.py

Test:

- [x] 00a: read config: check magic values

- [x] 00b: read mapping file, check magic values

- [x] 00c: read template file, check magic values

- [x] 01a -> 2a: `test_01a_read_posidents_from_file()`:

```py
     assert len(posidents) == 10
```

- [x] 01b -> 2b / 2c: `test_01b_read_posidents_from_db()`: all (10), vs sql (5)

- [x] 01c -? 2d/4b: `test_01_read_posidents_from_dict()`, add nonvalid posidents (-> 12)

- [x] 02a -> 3a: test if created XML is not empty and is valid, tag exists

- [x] 03a -> 1a : send XML, use invalid user/password, check http error code

- [x] 03b -> 1b: modify request XML (invalid service version), send, check http error code

- [x] 03c -> 3b/3c: send XML, check http error code, check response XML (not empty, is valid, check nonvalid posidents)

- [x] 04a: parse response XML, check dictionary

- [x] 04b: check number of keys == 10, check posident codes

- [x] 05a: write output json -> check non empty, is valid, read json, check number of keys, posidents code

- [x] 05b: write output db -> check non empty, is valid, read json, check number of keys, posidents code

TODO:

* check attribute mapping (?)

**Comment by landam** [comment]
@lindakladivova Please update

**Comment by lindakladivova** [comment]
Current tests fro CtiOS service:

- [x] 00a: read config: check magic values
- [x] 00b: read template file, check magic values

- [x] 01a: test if CtiOS service is working
- [x] 01b: test CtiOs service when put invalid password

- [x] 02a: read posidents from file
- [x] 02b: read posidents from db
- [x] 02c: read posidents from db (specified sql constraint)
- [x] 02d: read posidents from dict

- [x] 03a: check tags in requested XML after manual rendering     _for zeep will not be needed_
- [x] 03b: call service when XML is invalid      _also for zeep not needed?_

- [x] 03c: check response XML
- [x] 03d: parse XML into dictionary and check results

- [x] 04a: check posident types after processing the request (invalid, expired etc.)

- [x] 05a check writing the output to JSON
- [x] 05b check writing the output to CSV
- [x] 05c check mapping file used for attributes in DB and XML
- [x] 05d check writing the output to DB

**Comment by lindakladivova** [comment]
closed by #36 - tests for both modules
